server:
  port: 8000
spring:
  application:
    name: @pom.artifactId@
  datasource:
    url: jdbc:mysql://47.100.2.226:10000/snow?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  liquibase:
    enabled: true
    change-log: "classpath:liquibase/change_log/index.xml"
    contexts: dev